version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports: ["2181:2181"]
    networks: [bigdata]

  spark-master-1:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master-1
    environment:
      - SPARK_MASTER_HOST=spark-master-1
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper:2181 -Dspark.deploy.zookeeper.dir=/spark
    ports: ["8080:8080","7077:7077"]
    volumes:
      - ./spark-conf:/opt/hadoop/etc/hadoop:ro
      - ./java-spark-app/:/opt/spark-app
    networks: [bigdata]
    depends_on: [zookeeper]

  spark-master-2:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master-2
    environment:
      - SPARK_MASTER_HOST=spark-master-2
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8081
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper:2181 -Dspark.deploy.zookeeper.dir=/spark
    ports: ["8081:8081","7078:7077"]
    volumes:
      - ./spark-conf:/opt/hadoop/etc/hadoop:ro
      - ./java-spark-app/:/opt/spark-app
    networks: [bigdata]
    depends_on: [zookeeper]

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
    - SPARK_MASTER=spark://spark-master-1:7077,spark-master-2:7077
    - SPARK_WORKER_WEBUI_PORT=8082
    - SPARK_WORKER_DIR=/data/spark-worker
    - SPARK_LOCAL_DIRS=/data/spark-worker
    - SPARK_WORKER_OPTS=-Dspark.worker.cleanup.enabled=true
    ports:
      - "8082:8082"
    volumes:
    - ./spark-conf:/opt/hadoop/etc/hadoop:ro
    networks: [bigdata]

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
    - SPARK_MASTER=spark://spark-master-1:7077,spark-master-2:7077
    - SPARK_WORKER_WEBUI_PORT=8082
    - SPARK_WORKER_DIR=/data/spark-worker
    - SPARK_LOCAL_DIRS=/data/spark-worker
    - SPARK_WORKER_OPTS=-Dspark.worker.cleanup.enabled=true
    ports:
      - "8083:8083"
    volumes:
    - ./spark-conf:/opt/hadoop/etc/hadoop:ro
    networks: [bigdata]

  spark-worker-3:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-3
    hostname: spark-worker-3
    environment:
    - SPARK_MASTER=spark://spark-master-1:7077,spark-master-2:7077
    - SPARK_WORKER_WEBUI_PORT=8082
    - SPARK_WORKER_DIR=/data/spark-worker
    - SPARK_LOCAL_DIRS=/data/spark-worker
    - SPARK_WORKER_OPTS=-Dspark.worker.cleanup.enabled=true
    ports:
      - "8084:8084"
    volumes:
    - ./spark-conf:/opt/hadoop/etc/hadoop:ro
    networks: [bigdata]

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"  
      - "9000:9000"  
    environment:
      - CLUSTER_NAME=test-cluster 
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000  
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - HDFS_CONF_dfs_replication=3
    networks: [bigdata]

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    ports:
      - 9864:9864
      - 9865:9865
    depends_on:
      - namenode  
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000  
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - HDFS_CONF_dfs_replication=3
    networks: [bigdata]

networks:
  bigdata: {}